apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 'v1.19.0'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  values:
    operatorNamespace: rook-ceph
    monitoring:
      enabled: false
    cephClusterSpec:
      dashboard:
        enabled: true
      storage:
        useAllNodes: true
        useAllDevices: true
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true