---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  path: ./infrastructure/sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  dependsOn: 
    - name: sources
  path: ./config/crd
  sourceRef:
    kind: GitRepository
    name: metallb
  interval: 10m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn: 
    - name: sources
    - name: metallb-crds
  path: ./infrastructure/metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-base
  namespace: flux-system
spec:
  path: ./infrastructure/rook-ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-base
  path: ./infrastructure/rook-ceph/operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph
    - name: metallb-configuration
  path: ./infrastructure/rook-ceph/cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true