---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  path: ./infrastructure/sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  dependsOn: 
    - name: sources
  path: .charts/metallb/charts/crds
  sourceRef:
    kind: GitRepository
    name: metallb
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn: 
    - name: sources
    - name: metallb-crds
  path: ./infrastructure/metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true